-- Baseline migration for Gamified Study Hub backend foundation.
-- No business domain tables are created in this step.
-- UUID IDs are generated by Hibernate (GenerationType.UUID).

CREATE EXTENSION IF NOT EXISTS pgcrypto;
